Fix: correctly load required stud part
resolves running bare bone against LS 8.0 SNAPSHOT:
```
NoMethodError: undefined method `stoppable_sleep' for Stud:Module
```